name: Build Session and Httpserver (Stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Session
        shell: pwsh
        run: |
          mkdir bin
          cd app\interface\session\cmd\session
          go build -o ..\..\..\..\..\bin\session.exe
          cd ..\..\..\..\..

      - name: Build Httpserver
        shell: pwsh
        run: |
          cd app\interface\httpserver\cmd\httpserver
          go build -o ..\..\..\..\..\bin\httpserver.exe
          cd ..\..\..\..\..

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: teamgram-stable
          path: bin/
